### ISSUE TITLE
Images are never rendered to PDF

### ISSUE THREAD

**Issue by RomFouq** [trikita/slide#8]
Whatever the source of images (web or local), they are never rendered to PDF.

Great job for this app though !

**Comment by zserge** [comment]
@RomFouq Thanks for the feedback! Just pushed version 1.3, it should fix the issue. The reason was that the images were fetched asynchronously, so if the image was not in the cache during the PDF render - it was not rendered.

**Comment by RomFouq** [comment]
Thanks! I will test the fix when the app on F-Droid is updated.

**Comment by RomFouq** [comment]
Can you tag the 1.3 release, please? I think this should trigger the F-droid update.

**Comment by RomFouq** [comment]
Slide bas been updated on F-droid and it's fixed. Thanks!
